Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.9_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
r, size = 1., 2.
phirange = (0., 2*np.pi, 31)
zrange   = (-size, size, 31) 
phii, zj = 0, 10
xfun = lambda phi, z : r * np.cos(phi)
yfun = lambda phi, z : r * np.sin(phi)
zfun = lambda phi, z : z
gf.wfsurface(xfun, yfun, zfun, phirange, zrange, alpha = 0.6);
gf.wfmasterlines(xfun, yfun, zfun, phirange, zrange, ui = phii, vj = zj);
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-5-6010302539a2>[0m in [0;36m<module>[0;34m[0m
[1;32m      7[0m [0mzfun[0m [0;34m=[0m [0;32mlambda[0m [0mphi[0m[0;34m,[0m [0mz[0m [0;34m:[0m [0mz[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m [0mgf[0m[0;34m.[0m[0mwfsurface[0m[0;34m([0m[0mxfun[0m[0;34m,[0m [0myfun[0m[0;34m,[0m [0mzfun[0m[0;34m,[0m [0mphirange[0m[0;34m,[0m [0mzrange[0m[0;34m,[0m [0malpha[0m [0;34m=[0m [0;36m0.6[0m[0;34m)[0m[0;34m;[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 9[0;31m [0mgf[0m[0;34m.[0m[0mwfmasterlines[0m[0;34m([0m[0mxfun[0m[0;34m,[0m [0myfun[0m[0;34m,[0m [0mzfun[0m[0;34m,[0m [0mphirange[0m[0;34m,[0m [0mzrange[0m[0;34m,[0m [0mui[0m [0;34m=[0m [0mphii[0m[0;34m,[0m [0mvj[0m [0;34m=[0m [0mzj[0m[0;34m)[0m[0;34m;[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mTypeError[0m: wfmasterlines() missing 1 required positional argument: 'axes'

