Traceback (most recent call last):
  File "/Users/Xabier/Library/Python/3.9/lib/python/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/Xabier/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/Xabier/Library/Python/3.9/lib/python/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/Xabier/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/Xabier/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/Xabier/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
r, size = 1., 2.
phirange = (0., 2*np.pi, 31)
zrange   = (-size, size, 31) 
phii, zj = 0, 10
xfun = lambda phi, z : r * np.cos(phi)
yfun = lambda phi, z : r * np.sin(phi)
zfun = lambda phi, z : z
gf.wfsurface(xfun, yfun, zfun, phirange, zrange, alpha = 0.6);
gf.wfmasterlines(xfun, yfun, zfun, phirange, zrange, ui = phii, vj = zj);
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[5], line 9[0m
[1;32m      7[0m zfun [38;5;241m=[39m [38;5;28;01mlambda[39;00m phi, z : z
[1;32m      8[0m gf[38;5;241m.[39mwfsurface(xfun, yfun, zfun, phirange, zrange, alpha [38;5;241m=[39m [38;5;241m0.6[39m);
[0;32m----> 9[0m [43mgf[49m[38;5;241;43m.[39;49m[43mwfmasterlines[49m[43m([49m[43mxfun[49m[43m,[49m[43m [49m[43myfun[49m[43m,[49m[43m [49m[43mzfun[49m[43m,[49m[43m [49m[43mphirange[49m[43m,[49m[43m [49m[43mzrange[49m[43m,[49m[43m [49m[43mui[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[43mphii[49m[43m,[49m[43m [49m[43mvj[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[43mzj[49m[43m)[49m;

[0;31mTypeError[0m: wfmasterlines() missing 1 required positional argument: 'axes'

